require "json"
require "generators/thecore/workspace_context"

module Thecore
  # `rails thecore:check_practices` — a Ruby port of thecore_code_extension's
  # checkPractices.js, scoped to this ticket (thecore_generators#13) to the
  # Scaffold Files check and the Model concern check (per ADR 0004 in the
  # thecore repo). The Action Companion checks (thecore_generators#14) are
  # deliberately not part of this module yet.
  #
  # Unlike checkPractices.js, which only ever ran the Scaffold Files check in
  # ATOM context, Runner applies both checks uniformly to every context root
  # it scans — the host app root plus every ATOM under vendor/submodules/ by
  # default, or a single named ATOM.
  #
  # The Model check is rescoped per ADR 0001's consequence: since
  # Api::ModelName/RailsAdmin::ModelName concern files are no longer
  # generated by default, their plain absence is not a violation. Only an
  # orphan `include Api::X`/`RailsAdmin::X` (pointing at a missing concern
  # file) or a concern file present but missing its required marker is
  # flagged.
  module CheckPractices
    # One reported issue. `to_h` matches the JSON schema this ticket's
    # acceptance criteria specifies: file, line, message, severity, fixable,
    # code (a stable machine-readable identifier a future consumer, e.g. the
    # VS Code extension, can filter on without depending on `message` text).
    Violation = Struct.new(:file, :line, :message, :severity, :fixable, :code, keyword_init: true) do
      def to_h
        {
          "file" => file,
          "line" => line,
          "message" => message,
          "severity" => severity.to_s,
          "fixable" => fixable,
          "code" => code,
        }
      end
    end

    def self.run(app_root:, atom_name: nil)
      Runner.new(app_root: app_root, atom_name: atom_name).run
    end

    class Runner
      AFTER_INITIALIZE_MARKER = "Rails.application.configure do"
      ASSETS_MARKER = "Rails.application.config.assets.precompile"
      API_CONCERN_MARKERS = ["extend ActiveSupport::Concern", "cattr_accessor :json_attrs"].freeze
      RAILS_ADMIN_CONCERN_MARKERS = ["extend ActiveSupport::Concern", "rails_admin do"].freeze

      def initialize(app_root:, atom_name: nil)
        @app_root = app_root.to_s
        @atom_name = atom_name
      end

      def run
        context_roots.flat_map { |root| scaffold_file_violations(root) + model_violations(root) }
      end

      private

      # Delegates entirely to WorkspaceContext.atom_dir_for for the
      # `--atom=NAME` case, the same resolution+error-message logic
      # AtomAware uses for the Model/Migration/Root Action generators'
      # `--atom=NAME` - rather than re-deriving it here, which would leave
      # two copies of the same "no ATOM named X" message to keep in sync.
      # It raises Thor::Error (not a CheckPractices-specific class) on an
      # unknown name; the rake task rescues that directly.
      def context_roots
        if @atom_name
          [Thecore::Generators::WorkspaceContext.atom_dir_for(cwd: nil, app_root: @app_root, atom_name: @atom_name)]
        else
          [@app_root, *Thecore::Generators::WorkspaceContext.all_atom_dirs(@app_root)]
        end
      end

      def scaffold_file_violations(root)
        check_scaffold_file(
          File.join(root, "config", "initializers", "after_initialize.rb"),
          AFTER_INITIALIZE_MARKER, "after_initialize.rb", "after_initialize"
        ) + check_scaffold_file(
          File.join(root, "config", "initializers", "assets.rb"),
          ASSETS_MARKER, "assets.rb", "assets"
        )
      end

      def check_scaffold_file(path, marker, label, code_prefix)
        unless File.exist?(path)
          return [Violation.new(
            file: path, line: 0, message: "Missing Scaffold File: #{label}",
            severity: :error, fixable: false, code: "missing_#{code_prefix}"
          )]
        end

        return [] if File.read(path).include?(marker)

        [Violation.new(
          file: path, line: 0, message: "#{label} is missing the `#{marker}` marker",
          severity: :error, fixable: false, code: "missing_#{code_prefix}_marker"
        )]
      end

      def model_violations(root)
        model_dir = File.join(root, "app", "models")
        return [] unless File.directory?(model_dir)

        Dir.children(model_dir).select { |f| f.end_with?(".rb") }.sort.flat_map do |file|
          check_model(root, file)
        end
      end

      def check_model(root, file)
        model_name = File.basename(file, ".rb").camelize
        model_content = File.read(File.join(root, "app", "models", file))

        check_concern(root, file, model_name, model_content, type: "api", module_prefix: "Api", markers: API_CONCERN_MARKERS) +
          check_concern(root, file, model_name, model_content, type: "rails_admin", module_prefix: "RailsAdmin", markers: RAILS_ADMIN_CONCERN_MARKERS)
      end

      def check_concern(root, file, model_name, model_content, type:, module_prefix:, markers:)
        # A plain #include? substring check would false-positive: "include
        # Api::Foo" is itself a substring of "include Api::FooBar" (no
        # separator between them), so a model happening to include a
        # differently-named, longer concern would wrongly look like it
        # includes this one too. The negative lookahead requires whatever
        # follows the constant name to not itself be a constant-name
        # character.
        return [] unless model_content.match?(/include #{Regexp.escape("#{module_prefix}::#{model_name}")}(?![A-Za-z0-9_])/)

        concern_path = File.join(root, "app", "models", "concerns", type, file)
        unless File.exist?(concern_path)
          return [Violation.new(
            file: concern_path, line: 0,
            message: "#{model_name}: includes #{module_prefix}::#{model_name} but its concern file is missing",
            severity: :error, fixable: false, code: "orphan_#{type}_include"
          )]
        end

        concern_content = File.read(concern_path)
        markers.reject { |marker| concern_content.include?(marker) }.map do |marker|
          Violation.new(
            file: concern_path, line: 0,
            message: "#{model_name}: #{type} concern missing '#{marker}' marker",
            severity: :error, fixable: false, code: "#{type}_concern_missing_marker"
          )
        end
      end
    end

    module Reporter
      module_function

      def text(violations)
        return "✅ No violations found.\n" if violations.empty?

        violations
          .group_by(&:file)
          .sort
          .map { |file, file_violations| text_for_file(file, file_violations) }
          .join("\n\n") + "\n"
      end

      def text_for_file(file, violations)
        lines = violations.map { |v| "  [#{v.severity.to_s.upcase}] #{v.message}" }
        "#{file}:\n#{lines.join("\n")}"
      end
      private_class_method :text_for_file

      def json(violations)
        JSON.generate({ "violations" => violations.map(&:to_h) })
      end
    end
  end
end
