name: CI

on:
  push:
    branches: [ release/3 ]
  pull_request:
    branches: [ release/3 ]

jobs:
  test:
    name: Test suite
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run test suite
        run: bundle exec rake test
